# Build Android version of the app

name: Android

on:
  push:
    branches:
      - master
  
jobs:

  build:
    runs-on: macos-latest

    env:
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.3'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.6
    - name: Create key file
      run: "echo $KEY_JKS | base64 -d > key.jks"
    - name: Collect Translation Files
      run: |
        cd lib/l10n
        python3 collect_translations.py
    - name: Build for Android
      run: |
        flutter pub get
        cp lib/dummy_dsn.dart lib/dsn.dart
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
    - uses: actions/upload-artifact@v3
      with:
        name: apk-release
        path: build/app/outputs/apk/release/
